#!/bin/bash
#
# Script to create and run docker-heat image.
#
set -x
set -e

# Check for Root user
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root or with sudo"
    exit 1
fi

# Configure the Heat Image Name
export HEAT_IMAGE_NAME="${HEAT_IMAGE_NAME:-heat}"

# Configure the Heat Container Name
export HEAT_CONTAINER_NAME="${HEAT_CONTAINER_NAME:-heat}"

# Configure the Heat Hostname
export HEAT_HOSTNAME="${HEAT_HOSTNAME:-$HOSTNAME}"

# Configure the Heat Hostname
export DNS_SEARCH="${DNS_SEARCH:-example.com}"

docker run --privileged -d -h $HEAT_HOSTNAME --dns-search $DNS_SEARCH -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 8000:8000 -p 8004:8004 --name="$HEAT_CONTAINER_NAME" $HEAT_IMAGE_NAME

# Get the PID of the Heat Container
HEAT_CONTAINER_PID="$(docker inspect --format={{.State.Pid}} $HEAT_CONTAINER_NAME)"

#Use nsenter to enter the namespaces of the running Heat container.
nsenter -m -u -n -i -p -t $HEAT_CONTAINER_PID /bin/bash

exit $?
